name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build
        run: |
          make build

      - name: Run
        run: |
          ./git-prep-directory --url https://github.com/sensiblecodeio/git-prep-directory -ref main
